version: "3.8"
services:
  server:
    build:
      dockerfile: Dockerfile
      context: ./server
    ports:
      - "3001:3001" # Server (Node.js)
    volumes:
      - /app/node_modules
      - ./server:/app
    restart: unless-stopped

  client:
    build:
      dockerfile: Dockerfile
      context: ./client
    ports:
      - "8080:8080"    # Client (React App)
      - "1935:1935"    # RTMP Server (Nginx)
    depends_on:
      - server
    restart: unless-stopped
