version: "3.8"
services:
  server:
    build:
      dockerfile: Dockerfile
      context: ./server
    ports:
      - "3001:3001"
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - NODE_ENV=development
    restart: unless-stopped

  client:
    build:
      dockerfile: Dockerfile
      context: ./client
      args:
        - VITE_API_URL=http://localhost:3001
    ports:
      - "8080:8080"    # Web 界面
      - "1935:1935"    # RTMP 串流 (供未來 HLS 使用)
    depends_on:
      - server
    restart: unless-stopped
